# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_media'),
    ]

    operations = [
        migrations.DeleteModel(
            name='media',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
