# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20190109_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.CharField(blank=True, default='0', max_length=120, null=True),
        ),
    ]
