# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_auto_20190109_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stock',
            field=models.TextField(default='0'),
        ),
    ]
