# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_auto_20190109_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1', max_digits=20),
        ),
    ]
