# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20190109_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=profiles.models.upload_image_path),
        ),
    ]
